### ISSUE TITLE
Websocket errors on restart

### ISSUE THREAD

**Issue by Mystere** [nicehash/NiceHashMiner#193]
I have NiceHash set to auto-load on restart, I use Task Scheduler to wait 30 seconds, and run NHML with evelated rights.

When it boots, it always gives a bad gateway error.  If I wait a little bit of time, it will start working correctly, but dialog box that says it cannot retrieve performance data stays.. and thus it won't start mining.  Here is the relevant info from the debug console:

```
08/21/2017 01:51:23|Debug|WebSocket.sendHttpRequest|A request to the server:
                          GET /v2/nhm HTTP/1.1
                          User-Agent: websocket-sharp/1.0
                          Host: api.nicehash.com
                          Upgrade: websocket
                          Connection: Upgrade
                          Sec-WebSocket-Key: xxxxxxxxxxxxxxxxxxxxxxxxxx
                          Sec-WebSocket-Version: 13
08/21/2017 01:51:23|Debug|WebSocket.sendHttpRequest|A response to this request:
                          HTTP/1.1 502 Bad Gateway
                          Date: Mon, 21 Aug 2017 06:51:23 GMT
                          Content-Type: text/html; charset=UTF-8
                          Transfer-Encoding: chunked
                          Connection: keep-alive
                          Set-Cookie: __cfduid=d807d7313afea4c9b5dd49ffc2e0d34391503298283; expires=Tue, 21-Aug-18 06:51:23 GMT; path=/; domain=.nicehash.com; HttpOnly
                          Expires: Thu, 01 Jan 1970 00:00:01 GMT
                          Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
                          Pragma: no-cache
                          X-Frame-Options: SAMEORIGIN
                          Server: cloudflare-nginx
                          CF-RAY: 391ba9dd38343840-ATL
08/21/2017 01:51:23|Fatal|WebSocket.connect|Not a WebSocket handshake response.
08/21/2017 01:51:23|Debug|WebSocket.closeHandshake|Was clean?: False
                            sent: False
                            received: False
[01:51:23] [SOCKET] Connection closed: An error has occurred while connecting.
```

It does this several times, failing on all of them.  I do not believe this is a problem here, as this does not occur when i run an older version of the miner.  Also, the internet connection is fine at this time (i can browse just fine, even though NH is giving gateway error)

I believe this is related to https://github.com/nicehash/NiceHashMinerLegacy/issues/166

However, this is a bit more detailed, relating specifically to the WebSocket issue

**Comment by sebeksd** [comment]
When I did debug NHML I also recived "HTTP/1.1 502 Bad Gateway" multiply times like you but not always.
So generally WebSockets "HTTP/1.1 502 Bad Gateway" is one problem, not waiting enough for SMA result before autostarting is second problem and all of them are related.

**Comment by Mystere** [comment]
New errors.. these are even weirder...  redirecting to example.com?
```
8/21/2017 3:07:22 AM|Debug|WebSocket.sendHttpRequest|A request to the server:
                           GET /v2/nhm HTTP/1.1
                           User-Agent: websocket-sharp/1.0
                           Host: api.nicehash.com
                           Upgrade: websocket
                           Connection: Upgrade
                           Sec-WebSocket-Key: 
                           Sec-WebSocket-Version: 13
8/21/2017 3:07:22 AM|Debug|WebSocket.sendHttpRequest|A response to this request:
                           HTTP/1.1 301 Moved Permanently
                           Date: Mon, 21 Aug 2017 08:07:22 GMT
                           Transfer-Encoding: chunked
                           Connection: keep-alive
                           Cache-Control: max-age=3600
                           Expires: Mon, 21 Aug 2017 09:07:22 GMT
                           Location: http://example.com
                           Server: cloudflare-nginx
                           CF-RAY: 391c192b2acc834b-ATL
8/21/2017 3:07:22 AM|Warn |WebSocket.doHandshake|Received a redirection to 'http://example.com'.
8/21/2017 3:07:22 AM|Fatal|WebSocket.connect|Indicates the redirection.

```
